@startuml 家計簿

hide circle
hide method

package 家計簿データ集約 {
class 家計簿データ
}

package 入力ユーザー集約 {
class 入力ユーザー
class 大分類マスタ
class 支払い方法マスタ
class 購入者マスタ
class 小分類マスタ
class 内容マスタ

家計簿データ <- 入力ユーザー 
入力ユーザー <-- 大分類マスタ
入力ユーザー <--  支払い方法マスタ 
入力ユーザー <-- 購入者マスタ  


大分類マスタ <-- 小分類マスタ 
小分類マスタ <-- 内容マスタ

家計簿データ : 計上月
家計簿データ : 計上日
家計簿データ : 金額
家計簿データ : 大分類ID
家計簿データ : 大分類名
家計簿データ : 小分類ID
家計簿データ : 小分類名
家計簿データ : 内容ID
家計簿データ : 内容名
家計簿データ : 支払い方法ID
家計簿データ : 支払い方法名
家計簿データ : 購入者ID
家計簿データ : 購入者名

入力ユーザー : ユーザーID
入力ユーザー : ユーザー名
入力ユーザー : パスワード

大分類マスタ : ユーザーID
大分類マスタ : 大分類ID 
大分類マスタ : 大分類名

支払い方法マスタ : ユーザーID
支払い方法マスタ : 支払い方法ID
支払い方法マスタ : 支払い方法名

購入者マスタ : ユーザーID
購入者マスタ : 購入者ID
購入者マスタ : 購入者名

小分類マスタ : ユーザーID
小分類マスタ : 大分類ID 
小分類マスタ : 小分類ID 
小分類マスタ : 小分類名

内容マスタ : ユーザーID
内容マスタ : 小分類ID
内容マスタ : 内容ID
内容マスタ : 内容名
}

@enduml